---
title: "CV"
---

You can download my CV [here](images/CV_masl_2402.pdf).

## Publications

You can also check <https://portalcientifico.uam.es/es/ipublic/researcher/271101> or <https://scholar.google.es/schhp?hl=es>. 

### [in press]

<sup>45</sup> Martínez-Bacaicoa, J., **Sorrel, M. A.**, & Gámez-Guadix, M. (Manuscript accepted for publication) Development and Validation of Technology-Facilitated Sexual Violence Perpetration and Victimization Scales among Adults. *Assessment*.

<sup>44</sup> Ma, W., **Sorrel, M. A.**, Ge, Y., & Zhai, X. (Manuscript accepted for publication). A dual-purpose model for estimating ability and misconceptions. *Journal of Educational Measurement*.

<sup>43</sup> Kreitchmann, R. S., Nájera, P., Sanz, S., & **Sorrel, M. A.** (Manuscript accepted for publication). Enhancing content validity assessment via item response theory modeling. *Psicothema*.

### [2023] 

<sup>42</sup> La Touche R, Castillejos-Carrasco-Muñoz R, Tapia-Toca MC, Pardo-Montero J, Lerma-Lara S, de la Rosa-Díaz I, **Sorrel, M. A.**, & Paris-Alemany A. (2023). Development and validation of the dizziness fear-avoidance behaviours and beliefs inventory for patients with vestibular disorders. *PeerJ*, 11:e15940, https://doi.org/10.7717/peerj.15940 

<sup>41</sup> **Sorrel, M. A.**, Escudero, S., Nájera, P., Kreitchmann, R. S., & Vázquez-Lira, R. (2023). Exploring approaches for estimating parameters in cognitive diagnosis models with small sample sizes. *Psych*, *5*(2), 336-349. https://doi.org/10.3390/psych5020023 

<sup>40</sup> Nájera, P., Abad, F. J., & **Sorrel, M. A.** (2023). Is EFA always to be preferred? A systematic comparison of factor analytic techniques throughout the confirmatory-exploratory continuum. *Psychological Methods*. https://doi.org/10.1037/met0000579

<sup>39</sup> Nájera, P., Abad, F.J., Chiu, C-Y., & **Sorrel, M.A.** (2023). A Comprehensive Cognitive Diagnostic Method for Classroom-Level Assessments. *Journal of Educational and Behavioral Statistics*. https://doi.org/10.1037/10769986231158829

<sup>38</sup> Sanz, S., Kreitchmann, R. S., Nájera, P., Moreno, J. D., Martínez-Huertas, J. A., & **Sorrel, M. A.** (2023). FoCo: A Shiny app for formative assessment using cognitive diagnosis modeling. *Educational Psychology*, *29*(2), 149-158. https://doi.org/10.5093/psed2022a14

<sup>37</sup> Horcajo, J., Gil, Rafael, & **Sorrel, M. A.** (2023). Adaptation to Spanish of the Need for Affect Questionnaire Need for affect scale validation. *Psicothema*, *35*(3) 279-289. https://doi.org/10.7334/psicothema2022.328 

<sup>36</sup> Collado, S., Fidalgo, C., Rodriguez-Rey, & **Sorrel, M. A.**. (2023), Development of a self-efficacy scale for writing and defending academic texts. *Psicología Educativa*. *29*(1) 91-99. https://doi.org/10.5093/psed2022a15 

### [2022] 

<sup>35</sup> Gámez-Guadix, M., **Sorrel, M. A.**, & Martínez-Bacaicoa, J. Technology facilitated sexual violence perpetration and victimization among adolescents: A network analysis (2022). *Sexuality Research and Social Policy*. https://doi.org/10.1007/s13178-022-00775-y 

<sup>34</sup> Kreitchmann, R. S., de la Torre, J., **Sorrel, M. A.**, Nájera, P., & Abad, F. J. (2022). Improving reliability estimation in cognitive diagnosis modeling. *Behavior Research Methods*, 1-15. https://doi.org/10.3758/s13428-022-01967-5

<sup>33</sup> Gutierrez, F., Aluja, A., Ruiz-Rodríguez, J., Peri, J., Gárriz, M., García, L., **Sorrel, M. A.**, Sureda, B., Vall, G., Ferrer, M., & Calvo, N. Borderline, Where Are You? A Psychometric and Symptomic Approach to the ICD-11 Personality Domains (2022). *Personality Disorders: Theory, Research, and Treatment*. https://doi.org/10.1037/per0000592

<sup>32</sup> Kreitchmann, R., **Sorrel, M. A.**, & Abad, F. J. (in press). On bank assembly and block selection in multidimensional forced-choice adaptive assessments. *Educational and Psychological Measurement*. https://doi.org/10.1177/00131644221087986

<sup>31</sup> Franco-Martínez, A., Alvarado, J., & **Sorrel, M. A.** (in press). Range restriction affects factor analysis: Normality, estimation, fit, loadings, and reliability. *Educational and Psychological Measurement*. https://doig.org/10.1177/00131644221081867

<sup>30</sup> Urieta, P. **Sorrel, M. A.**, Aluja, A., Balada, F., Lacomba, E., & García, L. F. Exploring the relationship between personality, decision-making styles, and problematic smartphone use. *Current Psychology*. https://doi.org/10.1007/s12144-022-02731-w

<sup>29</sup> Abad, F. J., Kreitchmann, R. S., **Sorrel, M. A.**, Nájera, P., García-Garzón, E., Garrido, L. E., Jiménez, M. (2022). Building adaptive forced choice tests “on the fly” for personality measurement. *Papeles del Psicólogo*, 43, 29-35. https://doi.org/10.23923/pap.psicol.2982

### [2021] 

<sup>28</sup> Shi, Q., Ma, W., Robitzsch, A., Sorrel, M. A., Man, K. (2021). Cognitive diagnosis analysis in the G-DINA model using R. *Psych*, 3(4), 812-835. https://doi.org/10.3390/psych3040052

<sup>27</sup> Kreitchmann, R. S., Abad, F. J., & **Sorrel, M. A.** (in press). A genetic algorithm for optimal assembly of pairwise forced-choice questionnaires. *Behavior Research Methods*. https://doi.org/10.3758/s13428-021-01677-4

<sup>26</sup> **Sorrel, M. A.**, Aluja, A., García, L. F., & Gutiérrez, F. (in press). Psychometric Properties of the Five-Factor Personality Inventory for ICD-11 (FFiCD) in Spanish Community Samples. *Psychological Assessment*, 34(3), 281-293. https://doi.org/10.1037/pas0001084

<sup>25</sup> Aluja, A., **Sorrel, M. A.**, Garcia, L., García, O., & Gutiérrez, F. (in press). Factor convergence and predictive analysis of the Five Factor and Alternative Five Factor personality models with the Five-Factor Personality Inventory for ICD11 (FFiCD). *Journal of Personality Disorders*.

<sup>24</sup> **Sorrel, M. A.**, Nájera*, P., & Abad, F. J. (2021). cdcatR: An R Package for Cognitive Diagnostic Computerized Adaptive Testing. *Psych*, 3(4), 386-403. https://doi.org/10.3390/psych3030028

<sup>23</sup> **Sorrel, M. A.**, García, L. F., Aluja, A., Rolland, J. P., Rossier, J., Roskam , I.,  & Abad, F. J. (2021). Cross-Cultural Measurement Invariance in the Personality Inventory for DSM-5. *Psychiatry Research*. https://doi.org/10.1016/j.psychres.2021.114134

<sup>22</sup> Collado, S., Rodríguez-Rey, R., & **Sorrel, M. A.** (2021). Does beauty matter? The effect of perceived attractiveness on children’s moral judgments of harmful actions against animals. *Environment and Behavior*. doi:0013965211014626

<sup>21</sup> Nájera, P., Abad, F. J., & **Sorrel, M. A.** (2020). Determining the number of attributes in cognitive diagnosis modeling. *Frontiers in Psychology*. doi:10.3389/fpsyg.2021.614470

### [2020] 

<sup>20</sup> Nájera, P., **Sorrel, M. A.**, de la Torre, J., & Abad, F. J. (in press). Balancing fit and parsimony to improve Q-matrix validation. British Journal of Mathematical and Statistical Psychology. doi:10.1111/bmsp.12228

<sup>19</sup> **Sorrel, M. A.**, Abad, F.J., & Nájera, P. (2020). Improving accuracy and usage by correctly selecting: The effects of model selection in cognitive diagnosis computerized adaptive testing. *Applied Psychological Measurement*. doi:10.1177/0146621620977682

<sup>18</sup> **Sorrel, M. A.**, Martínez-Huertas, J. A., & Arconada, M. (2020). It must have been burnout: Prevalence and related factors among Spanish PhD students. *Spanish Journal of Psychology*.

<sup>17</sup> **Sorrel, M. A.**, Barrada, J. R., de la Torre, J., & Abad, F. J. (2020). Adapting cognitive diagnosis computerized adaptive testing item selection rules to traditional item response theory. *PLOS ONE*. doi:10.1371/journal.pone.0227196

<sup>16</sup> Nájera, P., **Sorrel, M.A.**, & de la Torre, J. Abad, F. J. (2020). Improving robustness in Q-matrix validation using an iterative and dynamic procedure. *Applied Psychological Measurement.* doi:10.1177/0146621620909904

### [2019] 

<sup>15</sup> Collado, S., & **Sorrel, M. A.** (2019). Children’s environmental moral judgments: Variations according to type of victim and exposure to nature. *Journal of Environmental Psychology*, *62*,42-48. 

<sup>14</sup> Nájera, P., **Sorrel, M. A.**, & Abad, F. J. (2019). Reconsidering cutoff points in the general method of empirical Q-matrix validation. *Educational and Psychological Measurement*, *79*, 727-753.

<sup>13</sup> Yigit, H., **Sorrel, M. A.**, & de la Torre, J. (2019). Computerized adaptive testing for cognitively based multiple-choice data. *Applied Psychological Measurement*, *43*, 388-401.

### [2018] 

<sup>12</sup> Abad, F. J., **Sorrel, M. A.**, García, L.F., & Aluja, A. (2018). Modeling general, specific, and method variance in personality measures: Results for ZKA-PQ and NEO-PI-R. *Assessment*, *25*, 959-977. 

### [2017] 

<sup>11</sup> Collado, S., Evans, G., & **Sorrel, M. A.** (2017). The role of parents and best friends in children’s pro-environmentalism: differences according to age and gender. *Journal of Environmental Psychology*, *54*, 27-37. 

<sup>10</sup> **Sorrel, M. A.**, de la Torre, J., Abad, F. J., & Olea, J. (2017). Two-step likelihood ratio test for item-level model comparison in cognitive diagnosis models. *Methodology*, *13*, 39-47.

<sup>9</sup> **Sorrel, M. A.**, Abad, F. J., Olea, J., de la Torre, J., & Barrada, J. R. (2017). Inferential item fit evaluation in cognitive diagnosis modeling. *Applied Psychological Measurement*, *41*, 614-631.

### [2016] 

<sup>8</sup> Collado, S., Staats, H., & **Sorrel, M. A.** (2016). A relational model of perceived restorativeness: Intertwined effects of obligations, familiarity, security and parental supervision. *Journal of Environmental Psychology*, *48*, 24-32.

<sup>7</sup> Cabello, R., **Sorrel, M. A.**, Fernández-Pinto, I., Extremera, N., & Fernández-Berrocal, P. (2016). Age and gender differences in ability emotional intelligence in adults: A cross-sectional study. *Developmental Psychology*, *52*, 1486-1492.

<sup>6</sup> **Sorrel, M. A.**, Olea, J., Abad, F. J., de la Torre, J., Aguado, D., & Lievens, F. (2016). Validity and reliability of situational judgement test scores: A new approach based on cognitive diagnosis models. *Organizational Research Methods*, *19*, 506-532.

<sup>5</sup> Collado, S., Staats, H., & **Sorrel, M. A.** (2016). Helping out on the land: Effects of children's role in agriculture on reported psychological restoration. *Journal of Environmental Psychology*, *45*, 201-209.

### [2015] 

<sup>4</sup> Abad, F. J., **Sorrel, M. A.**, Román, F. J., & Colom, R. (2015). The relationships between WAIS-IV factor index scores and educational level: A bifactor model approach. *Psychological Assessment*, *28*, 987-1000.

<sup>3</sup> Collado, S., Evans, G. W., Corraliza, J. A., & **Sorrel, M. A.** (2015). The role played by age on children's pro-ecological behaviors: An exploratory analysis. *Journal of Environmental Psychology*, *44*, 85-94.

<sup>2</sup> Lievens, F., Corstjens, J., **Sorrel, M. A.**, Abad, F. J., Olea, J., & Ponsoda, V. (2015). The cross‐cultural transportability of situational judgment tests: How does a US‐based integrity situational judgment test fare in España?. *International Journal of Selection and Assessment*, *23*, 361-372.

<sup>1</sup> Collado, S., Corraliza, J. A., **Sorrel, M. A.**, & W Evans, G. (2015). Spanish version of the Children’s Ecological Behavior (CEB) scale. *Psicothema*, *26*, 82-87.

### [Book Chapters]
de la Torre, J., & **Sorrel, M. A.** (2023). *Cognitive Diagnosis Models.* In F. Ashby, H. Colonius, & E. Dzhafarov (Eds.), New Handbook of Mathematical Psychology (Cambridge Handbooks in Psychology, pp. 385-420). Cambridge: Cambridge University Press. https://doi.org/10.1017/9781108902724.010 

### [Dissertation]
Advances in Cognitive Diagnosis Modeling (2018, April). You can find my dissertation here https://repositorio.uam.es/handle/10486/682712. It was co-advised by Francisco J. Abad and Julio Olea.